require:
  - rubocop-rails

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.0.0
  TargetRailsVersion: 6.1

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 30

Metrics/ParameterLists:
  Max: 6

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200

Rails:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
