# Basic Linux configuration
- hosts: web
  gather_facts: true
  become: true
  tags: commons
  roles:
    - role: common/time
    - role: common/journald
    - role: common/basic-pkgs
    - role: common/firewall
    - role: common/selinux
    - role: common/automatic-upgrades
    - role: common/users
    - role: common/fail2ban
    - role: common/sysctl
    - role: common/sshd
    - role: common/fish

# Podman container runtime
- hosts: web
  gather_facts: true
  become: true
  tags: podman
  roles:
    - role: podman/install
    - role: podman/autoupdater

# Containerized services
- hosts: web
  gather_facts: true
  become: true
  tags: services
  roles:
    - role: services/registry
      tags: registry

    - role: services/reverse-proxy/firewall-tunnel
      tags: reverse-proxy,firewall-tunnel

    - role: services/reverse-proxy/letsencrypt
      tags: reverse-proxy,letsencrypt

    - role: services/reverse-proxy/nginx
      tags: reverse-proxy,nginx

# Applications and websites
- hosts: web
  gather_facts: true
  become: true
  tags: apps
  roles:
    - role: apps/frontend
      tags: frontend
