# frozen_string_literal: true

require 'rails/engine'
require_relative 'presets'

module CKEditor5::Rails
  class Engine < ::Rails::Engine
    config.ckeditor5 = ActiveSupport::OrderedOptions.new

    # Specifies which CDN should be used to load CKEditor 5 using the ckeditor5_assets helper.
    # It is possible to use the following CDNs:
    # - :unpkg
    # - :jsdelivr (default)
    config.ckeditor5.default_cdn = :jsdelivr

    # Specifies configuration of editors generated by gem.
    config.ckeditor5.presets = PresetsManager.new

    initializer 'helper' do
      ActiveSupport.on_load(:action_view) do
        include Helpers
      end
    end

    def self.base
      config.ckeditor5
    end

    def self.configure
      yield config.ckeditor5
    end
  end
end
