# frozen_string_literal: true

require 'rails/engine'
require_relative 'presets'
require_relative 'hooks/form'

module CKEditor5::Rails
  class Engine < ::Rails::Engine
    config.ckeditor5 = ActiveSupport::OrderedOptions.new

    # Specifies configuration of editors generated by gem.
    config.ckeditor5.presets = PresetsManager.new

    initializer 'helper' do
      ActiveSupport.on_load(:action_view) do
        include Helpers
      end
    end

    initializer 'ckeditor5.simple_form' do
      next unless defined?(::SimpleForm)

      require_relative 'hooks/simple_form'

      ::SimpleForm::FormBuilder.map_type :ckeditor5, to: Hooks::SimpleForm::CKEditor5Input
    end

    initializer 'ckeditor5.form_builder' do
      require_relative 'hooks/form'

      ActionView::Helpers::FormBuilder.include(
        Hooks::Form::FormBuilderExtension
      )
    end

    def self.base
      config.ckeditor5
    end

    def self.default_preset
      config.ckeditor5.presets.default
    end

    def self.configure
      yield config.ckeditor5
    end
  end

  def configure(&block)
    Engine.configure(&block)
  end
end
