node_version: 20

all_groups:
  - name: wheel

  - name: containers

all_users:
  - name: app_front
    groups: containers,systemd-journal

  - name: nginx
    groups: containers,systemd-journal

  - name: registry
    groups: containers,systemd-journal

  - name: admin
    groups: wheel

local_paths:
  keys_dir: "{{ playbook_dir }}/keys"
  ssh_keys:
    authorized: "{{ playbook_dir }}/keys/authorized"

website:
  domain: ckeditor5-rails.mati365.ovh
  ssl: true

certbot:
  domains:
    - '{{ website.domain }}'

podman:
  containers_dir: /containers
  volumes_dir: /containers/volumes

  registry:
    credentials:
      username: '{{ lookup("ansible.builtin.env", "PODMAN_REGISTRY_USERNAME") }}'
      password: '{{ lookup("ansible.builtin.env", "PODMAN_REGISTRY_PASSWORD") }}'

apps:
  frontend:
    rails_master_key: '{{ lookup("ansible.builtin.env", "RAILS_MASTER_KEY") }}'
