name: Deploy Production

on:
  push:
    branches:
      - ovh/production
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag (default: github.sha)'
        required: false
        type: string

concurrency:
  group: deploy-frontend-ovh
  cancel-in-progress: false

jobs:
  deploy-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ckeditor5-rails.mati365.ovh
          username: ${{ secrets.PRODUCTION_PODMAN_REGISTRY_USERNAME }}
          password: ${{ secrets.PRODUCTION_PODMAN_REGISTRY_PASSWORD }}

      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ckeditor5-rails.mati365.ovh/app-frontend:latest
            ckeditor5-rails.mati365.ovh/app-frontend:${{ github.event.inputs.image_tag || github.sha }}
          cache-from: type=gha,scope=app-frontend
          cache-to: type=gha,scope=app-frontend,mode=max
          build-args: |
            "RAILS_MASTER_KEY=${{ secrets.PRODUCTION_RAILS_MASTER_KEY }}"
