name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 8 * * *'

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', '3.3']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Run Brakeman
      run: bundle exec brakeman --force --skip-files demo/

    - name: Run RuboCop
      run: bundle exec rubocop

    - name: Run spec tests
      run: bundle exec rake spec

    - name: Run e2e tests
      run: bundle exec rake e2e
      env:
        HEADLESS: true

    - name: Run build
      run: bundle exec rake build

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
