name: CKEditor Version Checker

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Run version checker
        id: version_check
        run: ruby bin/check_ckeditor_version.rb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Build npm_package
        run: npm run npm_package:build

      - name: Run e2e tests
        run: bundle exec rake e2e
        env:
          HEADLESS: true

      - name: Trigger Release Workflow
        if: steps.version_check.outputs.version_updated == 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-release
