name: CKEditor Version Checker

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Run version checker
        run: ruby .github/scripts/check_version.rb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
